# Generated by Django 3.2.8 on 2021-10-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('solicitud', models.IntegerField()),
                ('tiempoAtencion', models.IntegerField()),
            ],
        ),
    ]
